Documentation
ITU-BDSA2024-GROUP10/Chirp pull request #360
Opened 2024-12-16 09:22 UTC by RasmusLarsen02

2024-12-16 22:00 UTC, stoftot commented
I have made some modifications to documentation, clarifying and adding details, as well as removing unused methods from repos and services.

2024-12-17 12:59 UTC, math045b approved these changes

2024-12-17 13:41 UTC, stoftot approved these changes

2024-12-18 14:10 UTC, anthoncastillo approved these changes

2024-12-18 14:20 UTC, math045b requested changes

2024-12-18 14:20 UTC, math045b commented on Chirp/src/Chirp.Infrastructure/Model/Cheep.cs
> +/// The Cheep class represents the functionality of a Cheep; a 160-character long message that can be posted on the Chirp! application by a given Author.
"the functionality of" seems superfluous

2024-12-18 15:07 UTC, math045b approved these changes

2024-12-18 15:07 UTC, merged